config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :contacts

  resources :conversations do
    resources :posts
  end

  root to: "conversations#index"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/contact.rb
class Contact < ApplicationRecord
  has_many :posts, as: :author

  def display_name
    "#{name} <#{email}>"
  end
end

app/models/conversation.rb
class Conversation < ApplicationRecord
  belongs_to :contact
  has_many :posts, -> { order(created_at: :asc) }, dependent: :destroy

  def authors
    posts.includes(:author).map(&:author).uniq
  end
end

app/models/current.rb
class Current < ActiveSupport::CurrentAttributes
  attribute :host
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :conversation
  belongs_to :author, polymorphic: true
  has_rich_text :body
  has_many_attached :attachments

  validates :body, presence: true

  broadcasts_to :conversation
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action do
    Current.host = request.base_url
  end
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  before_action :set_contact, only: %i[ show edit update destroy ]

  # GET /contacts or /contacts.json
  def index
    @contacts = Contact.all
  end

  # GET /contacts/1 or /contacts/1.json
  def show
  end

  # GET /contacts/new
  def new
    @contact = Contact.new
  end

  # GET /contacts/1/edit
  def edit
  end

  # POST /contacts or /contacts.json
  def create
    @contact = Contact.new(contact_params)

    respond_to do |format|
      if @contact.save
        format.html { redirect_to @contact, notice: "Contact was successfully created." }
        format.json { render :show, status: :created, location: @contact }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @contact.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /contacts/1 or /contacts/1.json
  def update
    respond_to do |format|
      if @contact.update(contact_params)
        format.html { redirect_to @contact, notice: "Contact was successfully updated." }
        format.json { render :show, status: :ok, location: @contact }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @contact.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /contacts/1 or /contacts/1.json
  def destroy
    @contact.destroy
    respond_to do |format|
      format.html { redirect_to contacts_url, notice: "Contact was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_contact
      @contact = Contact.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def contact_params
      params.require(:contact).permit(:name, :email)
    end
end

app/controllers/conversations_controller.rb
class ConversationsController < ApplicationController
  #before_action :authenticate_user!
  before_action :set_conversation, only: %i[ show edit update destroy ]

  # GET /conversations or /conversations.json
  def index
    @conversations = Conversation.all
  end

  # GET /conversations/1 or /conversations/1.json
  def show
  end

  # GET /conversations/new
  def new
    @conversation = Conversation.new
  end

  # GET /conversations/1/edit
  def edit
  end

  # POST /conversations or /conversations.json
  def create
    @conversation = Conversation.new(conversation_params)

    respond_to do |format|
      if @conversation.save
        format.html { redirect_to @conversation, notice: "Conversation was successfully created." }
        format.json { render :show, status: :created, location: @conversation }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @conversation.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /conversations/1 or /conversations/1.json
  def update
    respond_to do |format|
      if @conversation.update(conversation_params)
        format.html { redirect_to @conversation, notice: "Conversation was successfully updated." }
        format.json { render :show, status: :ok, location: @conversation }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @conversation.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /conversations/1 or /conversations/1.json
  def destroy
    @conversation.destroy
    respond_to do |format|
      format.html { redirect_to conversations_url, notice: "Conversation was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_conversation
      @conversation = Conversation.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def conversation_params
      params.require(:conversation).permit(:contact_id, :subject)
    end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  #before_action :authenticate_user!
  before_action :set_conversation
  before_action :set_post, only: %i[ show edit update destroy ]

  # GET /posts or /posts.json
  def index
    redirect_to @conversation
  end

  # GET /posts/1 or /posts/1.json
  def show
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts or /posts.json
  def create
    @post = @conversation.posts.new(post_params)
    @post.author = current_user

    respond_to do |format|
      if @post.save
        ReplyJob.perform_later(@post)
        format.turbo_stream { render turbo_stream: turbo_stream.replace("form", partial: "posts/form", locals: { conversation: @conversation, post: Post.new }) }
        format.html { redirect_to @conversation, notice: "Post was successfully created." }
        format.json { render :show, status: :created, location: @post }
      else
        format.turbo_stream { render turbo_stream: turbo_stream.replace("form", partial: "posts/form", locals: { conversation: @conversation, post: @post }) }
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1 or /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: "Post was successfully updated." }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1 or /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: "Post was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = @conversation.posts.find(params[:id])
    end

    def set_conversation
      @conversation = Conversation.find(params[:conversation_id])
    end

    # Only allow a list of trusted parameters through.
    def post_params
      params.require(:post).permit(:conversation_id, :contact_id, :body, attachments: [])
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/conversations_helper.rb
module ConversationsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/contacts/_contact.html.erb
<div id="<%= dom_id contact %>" class="scaffold_record">
  <p>
    <strong>Name:</strong>
    <%= contact.name %>
  </p>

  <p>
    <strong>Email:</strong>
    <%= contact.email %>
  </p>

  <p>
    <%= link_to "Show this contact", contact %>
  </p>
</div>

app/views/contacts/_form.html.erb
<%= form_with(model: contact) do |form| %>
  <% if contact.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(contact.errors.count, "error") %> prohibited this contact from being saved:</h2>

      <ul>
        <% contact.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :email %>
    <%= form.text_field :email %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/contacts/edit.html.erb
<h1>Editing contact</h1>

<%= render "form", contact: @contact %>

<br>

<div>
  <%= link_to "Show this contact", @contact %> |
  <%= link_to "Back to contacts", contacts_path %>
</div>

app/views/contacts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Contact</h1>

<div id="contacts">
  <%= render @contacts %>
</div>

<%= link_to "New contact", new_contact_path %>

app/views/contacts/new.html.erb
<h1>New contact</h1>

<%= render "form", contact: @contact %>

<br>

<div>
  <%= link_to "Back to contacts", contacts_path %>
</div>

app/views/contacts/show.html.erb
<p id="notice"><%= notice %></p>

<%= render @contact %>

<div>
  <%= link_to "Edit this contact", edit_contact_path(@contact) %> |
  <%= link_to "Back to contacts", contacts_path %>

  <%= button_to "Destroy this contact", contact_path(@contact), method: :delete %>
</div>

app/views/conversations/_conversation.html.erb
<div id="<%= dom_id conversation %>" class="scaffold_record">
  <h1><%= conversation.subject %></h1>
  <p>
    <%= link_to "Show this conversation", conversation %>
  </p>
</div>

app/views/conversations/_form.html.erb
<%= form_with(model: conversation) do |form| %>
  <% if conversation.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(conversation.errors.count, "error") %> prohibited this conversation from being saved:</h2>

      <ul>
        <% conversation.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :contact_id, "To" %>
    <%= form.collection_select :contact_id, Contact.all, :id, :display_name %>
  </div>

  <div class="field">
    <%= form.label :subject %>
    <%= form.text_field :subject %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/conversations/edit.html.erb
<h1>Editing conversation</h1>

<%= render "form", conversation: @conversation %>

<br>

<div>
  <%= link_to "Show this conversation", @conversation %> |
  <%= link_to "Back to conversations", conversations_path %>
</div>

app/views/conversations/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Conversation</h1>

<div id="conversations">
  <%= render @conversations %>
</div>

<%= link_to "New conversation", new_conversation_path %>

app/views/conversations/new.html.erb
<h1>New conversation</h1>

<%= render "form", conversation: @conversation %>

<br>

<div>
  <%= link_to "Back to conversations", conversations_path %>
</div>

app/views/conversations/show.html.erb
<%= turbo_stream_from @conversation %>
<%= render @conversation %>

<div>
  <%= link_to "Edit this conversation", edit_conversation_path(@conversation) %> |
  <%= link_to "Back to conversations", conversations_path %>

  <%= button_to "Destroy this conversation", conversation_path(@conversation), method: :delete %>
</div>

<h3>Messages</h3>
<div id="posts">
  <%= render @conversation.posts %>
</div>

<h3>Reply</h3>
<%= render "posts/form", conversation: @conversation, post: Post.new %>

<%= link_to "Inbound email", new_rails_conductor_inbound_email_path(from: "Test User <test@example.com>", to: "conversation-#{@conversation.to_param}@example.com", subject: "RE: #{@conversation.subject}"), target: :_blank %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CustomerSupport</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/posts/_form.html.erb
<%= form_with(model: [conversation, post], id: "form") do |form| %>
  <% if post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
        <% post.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :body %>
    <%= form.rich_text_area :body %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/posts/_post.html.erb
<div id="<%= dom_id post %>" class="scaffold_record">
  <p>
  <strong><%= post.author.name %> (<%= post.author.email %>)</strong>
  </p>

  <p>
    <%= post.body %>
  </p>
</div>

app/views/posts/edit.html.erb
<h1>Editing post</h1>

<%= render "form", post: @post %>

<br>

<div>
  <%= link_to "Show this post", @post %> |
  <%= link_to "Back to posts", posts_path %>
</div>

app/views/posts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Post</h1>

<div id="posts">
  <%= render @posts %>
</div>

<%= link_to "New post", new_post_path %>

app/views/posts/new.html.erb
<h1>New post</h1>

<%= render "form", conversation: @conversation, post: @post %>

<br>

<div>
  <%= link_to "Back to conversation", conversation_path(@conversation) %>
</div>

app/views/posts/show.html.erb
<p id="notice"><%= notice %></p>

<%= render @post %>

<div>
  <%= link_to "Edit this post", edit_post_path(@post) %> |
  <%= link_to "Back to posts", posts_path %>

  <%= button_to "Destroy this post", post_path(@post), method: :delete %>
</div>